language: scala
scala:
  - 2.11.12
  - 2.12.8
  - 2.13.0

sudo: false

script: sbt ++$TRAVIS_SCALA_VERSION test

before_install:
  - rvm install 2.2.0
  - rvm use 2.2.0
  - gem install fluentd -v 1.6.2

jdk:
 - oraclejdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier
